### ISSUE TITLE
Create Webhooks for WaffleIO

### ISSUE THREAD

**Issue by MichalKononenko** [whitewhim2718/TopChef#4]
Can you go over to [this site](https://waffle.io/whitewhim2718/TopChef) and create the webhooks for waffle? This could be a useful thing to coordinate the project.

**Comment by whitewhim2718** [comment]
[![Stories in Ready](https://badge.waffle.io/whitewhim2718/TopChef.svg?label=ready&title=Ready)](http://waffle.io/whitewhim2718/TopChef)
Delete whitewhim2718/TopChef
Deleting a project will remove all of its data from waffle.io and unregister its webhooks to GitHub. Deleting a project will not affect any data in the GitHub repos that are connected to it.

Enter "whitewhim2718/TopChef" to confirm delete

**Comment by whitewhim2718** [comment]
Added webhooks.
