### ISSUE TITLE
Provide a basic routing map in the REST API

### ISSUE THREAD

**Issue by MichalKononenko** [whitewhim2718/TopChef#8]
**Issue Tracking Form**

I am 

- [ ] filing a bug report
- [X] filing a feature request
- [ ] asking a question about the system

**Bug Reports**

Please state the criticality of the bug

- [ ] showstopper, stops the site from functioning
- [ ] critical, prevents a part of the site from functioning in a way that breaks the feature
- [ ] annoying, mis-aligned images, bad CSS, text overflowing its container box

**Provide a description of the bug below**

**Feature Requests**

**Feature Title**

Provide a brief title for your FR. This and the issue number will be used as shorthand to work on issues.

*Title*: REST API Routing Map

**Description**:

I want to start with a front-to-back approach for designing the API. This means that we map out all the URLs first, and have them return some dummy data. The data can then come later as we set up SQLAlchemy. The routing table will look something like this

```
/users
/users/<int:user_id>
/users/<int:user_id>/experiment-sets
/users/<int:user_id>/experiment-sets/<int:set_id>
/users/<int:user_id>/experiment-sets/<int:set_id>/jobs
/users/<int:user_id>/experiment-sets/<int:set_id>/jobs/<int:job_id>

/programs
/programs/<int:program_id>
```

* Users will authenticate using Basic Authentication, ```username:password```. 
* Experiment sets consist of all the experiments that can be done on **one** NMR setup. In order to run experiments on a different set, the machine will need to be physically altered.
* Jobs consist of each individual pulse sequence
* The available pulse sequences will be available from a list of programs.

**Dependencies**:

If your feature request depends on other issues being resolved in order to
be implemented, please write them here. Be aware that as the project changes,
we will be editing this list of issues, so that we're aware of what needs to be
done first before we can get to work on it. Ensure that your dependency list
is formatted according to the template below

```
*My issue depends on*: [#1, #2, #3]
```

*My issue depends on*: #9 

**General Inquiries**

*Ask away! We won't bite!*

My question is: 

(question here)

**Comment by whitewhim2718** [comment]
I would prefer to keep the url scheme a bit shorter than "experiment-sets", but otherwise looks good!

**Comment by MichalKononenko** [comment]
Alright, we can cut out ```experiment-sets```. This may however limit our ability to separate our jobs into different setups.

**Comment by whitewhim2718** [comment]
No I mean just change it to like "expset" or something. It really doesn't matter, just readability vs length.
